export const ADD_LABEL = "ADD_LABEL";
export const EDIT_LABEL = "EDIT_LABEL";
export const REQUEST_ADD_LABEL = "REQUEST_ADD_LABEL";
export const CLOSE_LABEL_FORM = "CLOSE_LABEL_FORM";
export const REQUEST_EDIT_LABEL = "REQUEST_EDIT_LABEL";
